### ISSUE TITLE
I can not run it 

### ISSUE THREAD

**Issue by pikkoH** [anthonyesp/channel_selection#1]
1.i do not have the folder pathTL('turelabel.txt')where you mentioned in "divideTrainingTest.m",
2.how should i run your code ? there are too many folder, the only things i want to do is classify bci3a dataset 
please help me ,tkanks a lot!!!

**Comment by anthonyesp** [comment]
this was not referring to an issue but to bad execution of code.
however, some (unrelated) minor typos were fixed

**Comment by wuwobuhuan** [comment]
Hello, I would like to ask why the channel selection results for BCI2a motor imagery 2-class classification are different from our expected results.

**Comment by wuwobuhuan** [comment]
> 1.我没有您在“divideTrainingTest.m”中提到的文件夹路径TL('turelabel.txt')， 2.我应该如何运行您的代码？文件夹太多了，我唯一想做的就是对 bci3a 数据集进行分类 ，请帮帮我，非常感谢！！！

请问如何解决的
